version: '3.8'

services:
  test_app:
    image: test2_app
    container_name: tes2_app_1
    environment:
      - POSTGRES_PASSWORD=1234561
      - POSTGRES_USER=postgres
      - DATABASE=postgres 
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
  postgres:
    image: postgres:latest
    container_name: test_postgres_db
    restart: always 
    volumes:
      - .:/docker-entrypoint-initdb.d
      - postgress_data:/data
    environment:
      - POSTGRES_PASSWORD=1234561
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  postgress_data: