version: '3.4'

services:
  test2:
    image: test2
    container_name: test_app2
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - POSTGRES_PASSWORD=1234561
      - POSTGRES_USER=postgres
      - DATABASE=postgres 
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - APP_HOST=127.0.0.1
      - APP_PORT=8000
    volumes:
      - ./app:/code/app
      - storage:/storage:rw
    ports:
      - 8000:8000
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
  postgres:
    image: postgres:latest
    container_name: test_postgres_db
    restart: always 
    volumes:
      - .:/docker-entrypoint-initdb.d
      - postgress_data:/data
      - storage:/storage
    environment:
      - POSTGRES_PASSWORD=1234561
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  postgress_data:
  storage:
